#!/bin/sh /etc/rc.common
# Gateway agent (static Go binary)
START=99
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param envfile /opt/gateway-agent/config.env
	procd_set_param command /opt/gateway-agent/gateway-agent
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file /opt/gateway-agent/config.env
	procd_close_instance
}

stop_service() {
	killall gateway-agent 2>/dev/null
}
